config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tweets#index'
  resources :tweets, only: [:index, :create]
  resources :users do
    member do
      get :tweets
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
  default_scope -> { order('created_at DESC') }

  def self.from_users_followed_by(user)
    followed_user_ids = user.followed_user_ids
    where("user_id IN (?) OR user_id = ?", followed_user_ids, user)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def feed
    Tweet.from_users_followed_by(self)
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!, :only => [:create, :destroy]

  respond_to :html, :js

  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    respond_with @user
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    respond_with @user
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, :only => [:index, :create]
  before_action :current_user, :only => [:index, :create]

  def index
    @tweet  = current_user.tweets.build
    feed
  end

  def create
    @tweet = current_user.tweets.build(tweet_params)
    feed

    if @tweet.save
      redirect_to root_path
    else
      render 'index', status: 400, error: 'Tweet cannot be created'
    end
  end

  private

    def tweet_params
      params.require(:tweet).permit(:content, :user_id)
    end

    def feed
      @feed_items = current_user.feed
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitterati</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="row">
    <%= nav_bar :fixed => :top, :brand  => Twitterati, :responsive => true do %>
      <%= menu_group do %>
        <%= menu_item "Home", root_path %>
        <%= menu_item "Users", users_path %>
      <% end %>

      <%= menu_group :pull => :right do %>
        <%= render 'devise/menu/registration_items' %>
        <%= render 'devise/menu/login_items' %>
      <% end %>
    <% end %>
    <div class="col-lg-offset-3 col-lg-6 col-md-offset-3 col-md-6 col-sm-offset-2 col-sm-8 col-xs-12">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/tweets/_feed.html.erb
<ul class="tweets">
  <% @feed_items.each do |feed_item| %>
    <li id="<%= feed_item.id %>" class="feed-item well">
      <div class="user"><%= link_to feed_item.user.email, feed_item.user %></div>
      <div class="content well"><%= feed_item.content %></div>
    </li>
  <% end %>
</ul>

app/views/tweets/_tweet_form.html.erb
<%= form_for(@tweet, :html => {:role => 'form', :class => 'form tweet-form'}) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h4>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <div>Please tweet less than 140 characters.</div><br/>
    <%= f.text_area :content, :rows => 3, :class => 'col-md-5 col-lg-5 col-sm-8 input-text-area form-control' %>
    <div id="tweet_error_field" class="hide"></div>
  </div>
  
  <div class="actions">
    <%= f.submit class: 'btn btn-primary tweet-btn' %>
  </div>
<% end %>

app/views/tweets/index.html.erb
<div class="panel panel-info tweet-form-container">
  <div class="panel-heading">
    <h3 class="panel-title">What's happening?</h3>
  </div>
  <div class="panel-body">
    <div class="well">
      <%= render 'tweet_form' %>
    </div>
  </div>
</div>
<div class="panel panel-info feed-container">
  <div class="panel-heading">
    <h3 class="panel-title">Tweets</h3>
  </div>
  <div class="panel-body">
    <div class="well">
      <%= render 'feed' %>
    </div>
  </div>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id),
             remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/_user.html.erb
<li class="well">
  <%= link_to user.email, user %>
</li>

app/views/users/_users.html.erb
<div class="panel panel-info feed-container">
  <div class="panel-heading">
    <h3 class="panel-title">Users</h3>
  </div>
  <div class="panel-body">
    <div class="well">
      <% if @users.any? %>
        <ul class="users">
          <%= render @users %>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'users' %>

app/views/users/show.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <div>Email: <%= @user.email %></div>
  </div>
  <div class="panel-body">
    <div class="well">
      <%= render 'shared/stats' %>
      <%= render 'follow_form' if signed_in? %>  
    </div>
  </div>
</div>



<div class="panel panel-info feed-container">
  <div class="panel-heading">
    <h3 class="panel-title">Tweets by the User</h3>
  </div>
  <div class="panel-body">
    <div class="well">
      <% if @tweets.any? %>
        <ul class="users">
          <% @tweets.each do |tweet| %>
            <li class="tweet well">
              <%= tweet.content %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <div>Email: <%= @user.email %></div>
  </div>
  <div class="panel-body">
    <div class="well">
      <div><%= link_to "View My Profile", @user %></div>
      <div><b>Tweets:</b> <%= @user.tweets.count %></div>  
    </div>
    <div class="well">
      <%= render 'shared/stats' %>
    </div>
  </div>
</div>
<%= render 'users' %>